
Estructura de la tabla: artists
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'name', 'TEXT', 1, None, 0)
(2, 'mbid', 'TEXT', 0, None, 0)
(3, 'bio', 'TEXT', 0, None, 0)
(4, 'tags', 'TEXT', 0, None, 0)
(5, 'similar_artists', 'TEXT', 0, None, 0)
(6, 'begin_date', 'TEXT', 0, None, 0)
(7, 'end_date', 'TEXT', 0, None, 0)
(8, 'artist_type', 'TEXT', 0, None, 0)
(9, 'country', 'TEXT', 0, None, 0)
(10, 'disambiguation', 'TEXT', 0, None, 0)
(11, 'origin', 'TEXT', 0, None, 0)
(12, 'formed_year', 'INTEGER', 0, None, 0)
(13, 'aliases', 'TEXT', 0, None, 0)
(14, 'member_of', 'TEXT', 0, None, 0)
(15, 'spotify_url', 'TEXT', 0, None, 0)
(16, 'youtube_url', 'TEXT', 0, None, 0)
(17, 'discogs_url', 'TEXT', 0, None, 0)
(18, 'bandcamp_url', 'TEXT', 0, None, 0)
(19, 'rateyourmusic_url', 'TEXT', 0, None, 0)
(20, 'wikipedia_url', 'TEXT', 0, None, 0)
(21, 'wikipedia_content', 'TEXT', 0, None, 0)
(22, 'lastfm_url', 'TEXT', 0, None, 0)
(23, 'musicbrainz_url', 'TEXT', 0, None, 0)
(24, 'website', 'TEXT', 0, None, 0)
(25, 'allmusic_url', 'TEXT', 0, None, 0)
(26, 'setlistfm_url', 'TEXT', 0, None, 0)
(27, 'soundcloud_url', 'TEXT', 0, None, 0)
(28, 'instagram_url', 'TEXT', 0, None, 0)
(29, 'img_url', 'TEXT', 0, None, 0)
(30, 'img_urls', 'TEXT', 0, None, 0)
(31, 'listeners', 'TEXT', 0, None, 0)
(32, 'playcount', 'TEXT', 0, None, 0)
(33, 'last_updated', 'INTEGER', 0, None, 0)
(34, 'added_timestamp', 'INTEGER', 0, None, 0)

Estructura de la tabla: sqlite_sequence
(0, 'name', '', 0, None, 0)
(1, 'seq', '', 0, None, 0)

Estructura de la tabla: albums
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'artist_id', 'INTEGER', 0, None, 0)
(2, 'name', 'TEXT', 1, None, 0)
(3, 'year', 'INTEGER', 0, None, 0)
(4, 'originalyear', 'INTEGER', 0, None, 0)
(5, 'mbid', 'TEXT', 0, None, 0)
(6, 'release_group_mbid', 'TEXT', 0, None, 0)
(7, 'label', 'TEXT', 0, None, 0)
(8, 'genre', 'TEXT', 0, None, 0)
(9, 'total_tracks', 'INTEGER', 0, None, 0)
(10, 'media', 'TEXT', 0, None, 0)
(11, 'releasecountry', 'TEXT', 0, None, 0)
(12, 'catalognumber', 'TEXT', 0, None, 0)
(13, 'album_type', 'TEXT', 0, None, 0)
(14, 'spotify_url', 'TEXT', 0, None, 0)
(15, 'spotify_id', 'TEXT', 0, None, 0)
(16, 'youtube_url', 'TEXT', 0, None, 0)
(17, 'yt_id', 'TEXT', 0, None, 0)
(18, 'discogs_url', 'TEXT', 0, None, 0)
(19, 'bandcamp_url', 'TEXT', 0, None, 0)
(20, 'rateyourmusic_url', 'TEXT', 0, None, 0)
(21, 'wikipedia_url', 'TEXT', 0, None, 0)
(22, 'lastfm_url', 'TEXT', 0, None, 0)
(23, 'musicbrainz_url', 'TEXT', 0, None, 0)
(24, 'allmusic_url', 'TEXT', 0, None, 0)
(25, 'apple_url', 'TEXT', 0, None, 0)
(26, 'deezer_url', 'TEXT', 0, None, 0)
(27, 'amazon_url', 'TEXT', 0, None, 0)
(28, 'genius_url', 'TEXT', 0, None, 0)
(29, 'metacritic_url', 'TEXT', 0, None, 0)
(30, 'aoty_url', 'TEXT', 0, None, 0)
(31, 'scaruffi_rating', 'REAL', 0, None, 0)
(32, 'scaruffi_note', 'TEXT', 0, None, 0)
(33, 'aoty_user_score', 'INTEGER', 0, None, 0)
(34, 'aoty_critic_score', 'INTEGER', 0, None, 0)
(35, 'metacritic_score', 'INTEGER', 0, None, 0)
(36, 'cover_url', 'TEXT', 0, None, 0)
(37, 'album_art_path', 'TEXT', 0, None, 0)
(38, 'last_updated', 'INTEGER', 0, None, 0)
(39, 'added_timestamp', 'INTEGER', 0, None, 0)

Estructura de la tabla: album_metadata
(0, 'album_id', 'INTEGER', 0, None, 1)
(1, 'desc_lfm_album', 'TEXT', 0, None, 0)
(2, 'desc_lfm_artist', 'TEXT', 0, None, 0)
(3, 'desc_mb_album', 'TEXT', 0, None, 0)
(4, 'desc_mb_artist', 'TEXT', 0, None, 0)
(5, 'wikipedia_content', 'TEXT', 0, None, 0)
(6, 'producers', 'TEXT', 0, None, 0)
(7, 'engineers', 'TEXT', 0, None, 0)
(8, 'credits', 'TEXT', 0, None, 0)

Estructura de la tabla: genres
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'name', 'TEXT', 1, None, 0)
(2, 'source', 'TEXT', 0, None, 0)
(3, 'last_updated', 'INTEGER', 0, None, 0)

Estructura de la tabla: album_genres
(0, 'album_id', 'INTEGER', 1, None, 1)
(1, 'genre_id', 'INTEGER', 1, None, 2)
(2, 'weight', 'REAL', 0, '1.0', 0)

Estructura de la tabla: collections
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'slug', 'TEXT', 1, None, 0)
(2, 'name', 'TEXT', 1, None, 0)
(3, 'total_albums', 'INTEGER', 0, '0', 0)
(4, 'source_url', 'TEXT', 0, None, 0)
(5, 'source_type', 'TEXT', 0, None, 0)
(6, 'last_updated', 'INTEGER', 0, None, 0)
(7, 'added_timestamp', 'INTEGER', 0, None, 0)

Estructura de la tabla: collection_albums
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'collection_id', 'INTEGER', 1, None, 0)
(2, 'album_id', 'INTEGER', 1, None, 0)
(3, 'rank', 'INTEGER', 0, None, 0)

Estructura de la tabla: users
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'username', 'TEXT', 1, None, 0)
(2, 'lastfm_username', 'TEXT', 0, None, 0)
(3, 'added_timestamp', 'INTEGER', 0, None, 0)

Estructura de la tabla: user_heard
(0, 'user_id', 'INTEGER', 1, None, 1)
(1, 'album_id', 'INTEGER', 1, None, 2)
(2, 'first_heard_at', 'INTEGER', 0, None, 0)

Estructura de la tabla: sqlite_stat1
(0, 'tbl', '', 0, None, 0)
(1, 'idx', '', 0, None, 0)
(2, 'stat', '', 0, None, 0)

Estructura de la tabla: sqlite_stat4
(0, 'tbl', '', 0, None, 0)
(1, 'idx', '', 0, None, 0)
(2, 'neq', '', 0, None, 0)
(3, 'nlt', '', 0, None, 0)
(4, 'ndlt', '', 0, None, 0)
(5, 'sample', '', 0, None, 0)
